version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

networks:
  covid-net:
    name: covid-net

services:
  check:
    logging: *default-logging
    build:
      context: ./components/check/
      dockerfile: ./Dockerfile
    container_name: check
    volumes:
      - ./input:/covid19-reproductionNumber/input/
    command: python src/checkfile.py
    networks:
      - covid-net

  reff:
    logging: *default-logging
    build:
      context: ./components/reff/
      dockerfile: ./Dockerfile
    container_name: reff
    volumes:
      - ./input:/covid19-reproductionNumber/input/
      - ./output:/covid19-reproductionNumber/output/
    command: python src/reff_estimator.py
    depends_on:
      - check
    networks:
      - covid-net

  rt:
    logging: *default-logging
    build:
      context: ./components/rt/
      dockerfile: ./Dockerfile
    container_name: rt
    volumes:
      - ./input/:/home/matlab/covid19-reproductionNumber/input/
      - ./output/:/home/matlab/covid19-reproductionNumber/output/
      - ${MATLAB_LICENSE}:/license.dat
    working_dir: /home/matlab/covid19-reproductionNumber
    # Warning - `mac_address` to be tested (legacy)
    mac_address: 02:42:ac:12:00:04
    environment:
      - MLM_LICENSE_FILE=/license.dat
    command: matlab -r "run('src/rt_estimator.m'); exit();"
    depends_on:
      - check
    networks:
      - covid-net
